"""Brute-force MT19937 seed cracker for Grocery Bot.

Given the first 2 observed orders (active + preview), identifies the game seed
by testing candidate seeds until the generated orders match.

Orders are generated by Python's random.Random(seed) (MT19937). With ~12 RNG
calls total for 2 orders of 4-6 items each, the constraint is strong enough to
uniquely identify the seed within [0, 10M).

Expected runtime: < 3s on 8 cores for 10M range (Windows spawn).
"""
import os
import json
import sys
import time
import random
from multiprocessing import Pool

from configs import CONFIGS

_SOLUTIONS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'solutions')


# ── Inner loop (must be top-level for multiprocessing spawn pickling) ─────────

def crack_seed_chunk(chunk_start, chunk_end, order0_types, order1_types,
                     avail_types, available_counts, order_size):
    """Test seeds in [chunk_start, chunk_end). Returns matching seed or None.

    No external imports except random — safe for multiprocessing spawn workers.

    Args:
        avail_types: List of type-name strings in dict-insertion order.
        available_counts: Dict {type_name: count} — initial shelf counts.
        order_size: (lo, hi) tuple, e.g. (4, 6) for Expert.
    """
    rng = random.Random()
    o0 = tuple(order0_types)
    o1 = tuple(order1_types)
    n0 = len(o0)
    n1 = len(o1)
    lo, hi = order_size

    for seed in range(chunk_start, chunk_end):
        rng.seed(seed)

        # ── Order 0 ────────────────────────────────────────────────────────
        sz0 = rng.randint(lo, hi)
        if sz0 != n0:
            continue

        temp = dict(available_counts)
        ok0 = True
        for i in range(n0):
            usable = [t for t in avail_types if temp.get(t, 0) > 0]
            if not usable:
                usable = avail_types
            t = rng.choice(usable)
            if t != o0[i]:
                ok0 = False
                break
            if t in temp:
                temp[t] -= 1

        if not ok0:
            continue

        # ── Order 1 ────────────────────────────────────────────────────────
        sz1 = rng.randint(lo, hi)
        if sz1 != n1:
            continue

        temp = dict(available_counts)  # fresh counts — available_counts is per-order
        ok1 = True
        for i in range(n1):
            usable = [t for t in avail_types if temp.get(t, 0) > 0]
            if not usable:
                usable = avail_types
            t = rng.choice(usable)
            if t != o1[i]:
                ok1 = False
                break
            if t in temp:
                temp[t] -= 1

        if ok1:
            return seed

    return None


# ── Public API ────────────────────────────────────────────────────────────────

def crack_seed_fast(order0_types, order1_types, map_state, difficulty,
                    seed_range=(0, 10_000_000), n_workers=8):
    """Parallel seed cracker using multiprocessing.Pool (spawn-safe for Windows).

    Args:
        order0_types: List of type-name strings for order 0 (active order from WS).
        order1_types: List of type-name strings for order 1 (preview order from WS).
        map_state: MapState built from live capture (for available_counts).
        difficulty: Difficulty string ('easy', 'medium', 'hard', 'expert').
        seed_range: (start, end) exclusive-end range to search.
        n_workers: Number of parallel worker processes.

    Returns:
        Matching seed (int) or None if not found.
    """
    cfg = CONFIGS[difficulty]
    order_size = cfg['order_size']

    # Build available_counts in map_state's dict-insertion order (matches server).
    # map_state.items is sorted by (x, y) position — same order server uses.
    available_counts = {}
    for item in map_state.items:
        t = item['type']
        available_counts[t] = available_counts.get(t, 0) + 1

    # avail_types preserves dict insertion order (Python 3.7+)
    avail_types = [t for t, c in available_counts.items() if c > 0]

    start, end = seed_range
    total = end - start
    chunk_size = max(1, (total + n_workers - 1) // n_workers)

    chunks = []
    for i in range(n_workers):
        cs = start + i * chunk_size
        ce = min(cs + chunk_size, end)
        if cs < ce:
            chunks.append((cs, ce))

    t0 = time.time()
    print(f"[seed_crack] Searching seeds [{start}, {end}) in {len(chunks)} chunks "
          f"(n_workers={n_workers})...", file=sys.stderr)

    # Build args lists (all picklable)
    args = [
        (cs, ce,
         list(order0_types), list(order1_types),
         list(avail_types), dict(available_counts), order_size)
        for cs, ce in chunks
    ]

    with Pool(processes=n_workers) as pool:
        results = pool.starmap(crack_seed_chunk, args)

    dt = time.time() - t0

    for result in results:
        if result is not None:
            print(f"[seed_crack] Found seed={result} in {dt:.2f}s", file=sys.stderr)
            return result

    print(f"[seed_crack] No seed found in {seed_range} ({dt:.2f}s)", file=sys.stderr)
    return None


def save_cracked_seed(difficulty, seed, order0_types):
    """Cache cracked seed to solutions/<difficulty>/cracked_seed.json."""
    path = os.path.join(_SOLUTIONS_DIR, difficulty, 'cracked_seed.json')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump({'seed': seed, 'order0_types': list(order0_types)}, f)
    print(f"[seed_crack] Saved seed={seed} to {path}", file=sys.stderr)


def load_cracked_seed(difficulty, order0_types=None):
    """Return cached seed if still valid.

    Args:
        difficulty: Difficulty string.
        order0_types: Current first-order types to validate the cache.
                      If None, returns cached seed without validation.

    Returns:
        Seed (int) or None.
    """
    path = os.path.join(_SOLUTIONS_DIR, difficulty, 'cracked_seed.json')
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            data = json.load(f)
        cached_seed = data['seed']
        cached_order0 = data.get('order0_types', [])
        if order0_types is not None and list(order0_types) != list(cached_order0):
            print(f"[seed_crack] Cache invalid (order0 mismatch)", file=sys.stderr)
            return None
        print(f"[seed_crack] Loaded cached seed={cached_seed}", file=sys.stderr)
        return cached_seed
    except Exception as e:
        print(f"[seed_crack] Cache load failed: {e}", file=sys.stderr)
        return None


# ── CLI self-test ─────────────────────────────────────────────────────────────

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Test seed cracker')
    parser.add_argument('difficulty', default='expert', nargs='?',
                        choices=['easy', 'medium', 'hard', 'expert', 'nightmare'])
    parser.add_argument('seed', type=int, default=42, nargs='?')
    parser.add_argument('--range', type=int, default=10_000_000,
                        help='Search range [0, range)')
    parser.add_argument('--workers', type=int, default=8)
    args = parser.parse_args()

    from game_engine import build_map, generate_all_orders

    ms = build_map(args.difficulty)
    all_orders = generate_all_orders(args.seed, ms, args.difficulty)
    o0 = list(all_orders[0]._required_names)
    o1 = list(all_orders[1]._required_names)

    print(f"Testing crack_seed_fast for {args.difficulty} seed={args.seed}")
    print(f"  Order 0: {o0}")
    print(f"  Order 1: {o1}")

    found = crack_seed_fast(o0, o1, ms, args.difficulty,
                            seed_range=(0, args.range), n_workers=args.workers)
    if found == args.seed:
        print(f"PASS: found seed={found}")
    elif found is not None:
        print(f"FAIL: expected {args.seed}, got {found}")
    else:
        print(f"FAIL: seed not found in [0, {args.range})")
