"""
Export the best ensemble combination for submission.

Analyzes trained weights, picks the best N models that fit within the
420 MB / 3 weight file submission limit, and generates the run.py
needed for ensemble inference in the sandbox.

Usage:
  python export_for_submission.py --coco-dir /path/to/NM_NGD_coco_dataset/train
  python export_for_submission.py --pick yolov8x_seed0 yolov8x_seed42  # manual selection
  python export_for_submission.py --to-onnx  # export as ONNX (smaller)
"""

import argparse
import json
from pathlib import Path
import shutil

import torch

_original_torch_load = torch.load
def _patched_torch_load(*args, **kwargs):
    if "weights_only" not in kwargs:
        kwargs["weights_only"] = False
    return _original_torch_load(*args, **kwargs)
torch.load = _patched_torch_load


ROOT = Path(__file__).resolve().parent
WEIGHTS_DIR = ROOT / "weights"
EXPORT_DIR = ROOT / "export"

MAX_WEIGHT_FILES = 3
MAX_ZIP_MB = 420
# Reserve space for classifier.safetensors (~30MB) + Python files
WEIGHT_BUDGET_MB = 380


def strip_and_measure(pt_path):
    """Load checkpoint, strip optimizer, return size in MB."""
    ckpt = torch.load(str(pt_path), map_location="cpu", weights_only=False)
    ckpt["optimizer"] = None
    # Save to temp to measure
    tmp = pt_path.parent / f".tmp_{pt_path.name}"
    torch.save(ckpt, str(tmp))
    size_mb = tmp.stat().st_size / 1024 / 1024
    tmp.unlink()
    return size_mb


def select_best_combination(weight_files, budget_mb, max_files):
    """Select the best combination of models that fits in budget."""
    # Measure sizes
    sizes = {}
    for wf in weight_files:
        sizes[wf.name] = wf.stat().st_size / 1024 / 1024

    print(f"\nAvailable weights ({len(weight_files)}):")
    for wf in weight_files:
        print(f"  {wf.name}: {sizes[wf.name]:.1f} MB")

    # Sort by name to prioritize yolov8x over yolov8l
    sorted_files = sorted(weight_files, key=lambda f: (
        0 if "yolov8x" in f.name else 1,  # prefer x over l
        f.name
    ))

    # Greedy: pick models until budget/count is exhausted
    selected = []
    total_mb = 0
    for wf in sorted_files:
        if len(selected) >= max_files:
            break
        if total_mb + sizes[wf.name] > budget_mb:
            continue
        selected.append(wf)
        total_mb += sizes[wf.name]

    return selected, total_mb


def generate_ensemble_run_py(model_names, wbf_iou=0.55):
    """Generate the run.py that performs ensemble inference in the sandbox."""
    # Build the model list string
    models_str = ", ".join(f'"{name}"' for name in model_names)

    return f'''"""
NorgesGruppen Object Detection — Ensemble Inference

Runs {len(model_names)} YOLO models and merges predictions with Weighted Boxes Fusion.
Generated by export_for_submission.py.

Usage: python run.py --input /data/images --output /output/predictions.json
"""

import argparse
import json
import time
import numpy as np
from pathlib import Path

import torch
import torch.nn.functional as F

_original_torch_load = torch.load
def _patched_torch_load(*args, **kwargs):
    if "weights_only" not in kwargs:
        kwargs["weights_only"] = False
    return _original_torch_load(*args, **kwargs)
torch.load = _patched_torch_load

from ultralytics import YOLO

try:
    from torchvision.ops import nms as tv_nms
except ImportError:
    tv_nms = None

SCRIPT_DIR = Path(__file__).resolve().parent
MODEL_NAMES = [{models_str}]

IMGSZ = 1536
CONF = 0.001
IOU_NMS = 0.6
MAX_DET = 3000
TIMEOUT_SECONDS = 285
WBF_IOU = {wbf_iou}


def wbf_single_image(boxes_list, scores_list, labels_list, img_w, img_h,
                      iou_thr=WBF_IOU, skip_thr=0.001, weights=None):
    """Weighted Boxes Fusion for a single image (pure numpy, no external deps).

    Each input list has one entry per model.
    Boxes are in xyxy pixel coordinates.
    """
    if weights is None:
        weights = [1.0] * len(boxes_list)

    # Normalize to [0, 1]
    all_boxes, all_scores, all_labels, all_weights = [], [], [], []
    for i, (boxes, scores, labels) in enumerate(zip(boxes_list, scores_list, labels_list)):
        if len(boxes) == 0:
            continue
        norm = boxes.copy().astype(np.float64)
        norm[:, [0, 2]] /= img_w
        norm[:, [1, 3]] /= img_h
        np.clip(norm, 0, 1, out=norm)
        for j in range(len(boxes)):
            if scores[j] < skip_thr:
                continue
            all_boxes.append(norm[j])
            all_scores.append(float(scores[j]) * weights[i])
            all_labels.append(int(labels[j]))
            all_weights.append(weights[i])

    if not all_boxes:
        return np.empty((0, 4)), np.empty(0), np.empty(0, dtype=int)

    all_boxes = np.array(all_boxes)
    all_scores = np.array(all_scores)
    all_labels = np.array(all_labels)

    # Sort by score descending
    order = np.argsort(-all_scores)
    all_boxes = all_boxes[order]
    all_scores = all_scores[order]
    all_labels = all_labels[order]

    # Cluster boxes by class and IoU
    clusters = []  # list of (summed_box, total_weight, count, label, max_score)
    used = np.zeros(len(all_boxes), dtype=bool)

    for i in range(len(all_boxes)):
        if used[i]:
            continue
        label = all_labels[i]
        box_i = all_boxes[i]
        cluster_box = box_i * all_scores[i]
        cluster_weight = all_scores[i]
        cluster_count = 1
        max_score = all_scores[i]
        used[i] = True

        for j in range(i + 1, len(all_boxes)):
            if used[j] or all_labels[j] != label:
                continue
            # Compute IoU
            box_j = all_boxes[j]
            xx1 = max(box_i[0], box_j[0])
            yy1 = max(box_i[1], box_j[1])
            xx2 = min(box_i[2], box_j[2])
            yy2 = min(box_i[3], box_j[3])
            inter = max(0, xx2 - xx1) * max(0, yy2 - yy1)
            area_i = (box_i[2] - box_i[0]) * (box_i[3] - box_i[1])
            area_j = (box_j[2] - box_j[0]) * (box_j[3] - box_j[1])
            iou = inter / (area_i + area_j - inter) if (area_i + area_j - inter) > 0 else 0

            if iou > iou_thr:
                cluster_box += all_boxes[j] * all_scores[j]
                cluster_weight += all_scores[j]
                cluster_count += 1
                max_score = max(max_score, all_scores[j])
                used[j] = True
                # Update reference box to cluster average
                box_i = cluster_box / cluster_weight

        avg_box = cluster_box / cluster_weight
        # Score: average boosted by number of models agreeing
        fused_score = max_score * min(cluster_count, len(boxes_list)) / len(boxes_list)
        clusters.append((avg_box, fused_score, label))

    if not clusters:
        return np.empty((0, 4)), np.empty(0), np.empty(0, dtype=int)

    out_boxes = np.array([c[0] for c in clusters])
    out_scores = np.array([c[1] for c in clusters])
    out_labels = np.array([c[2] for c in clusters], dtype=int)

    # Denormalize
    out_boxes[:, [0, 2]] *= img_w
    out_boxes[:, [1, 3]] *= img_h

    return out_boxes, out_scores, out_labels


def run_inference(input_dir, output_path):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {{device}}, Models: {{len(MODEL_NAMES)}}")
    start_time = time.time()

    input_dir = Path(input_dir)
    output_path = Path(output_path)

    # Load all models
    models = []
    for name in MODEL_NAMES:
        pt = SCRIPT_DIR / name
        print(f"Loading {{name}}...")
        models.append(YOLO(str(pt)))
    print(f"All models loaded in {{time.time() - start_time:.1f}}s")

    image_files = sorted(
        list(input_dir.glob("*.jpg")) +
        list(input_dir.glob("*.jpeg")) +
        list(input_dir.glob("*.png"))
    )
    print(f"Found {{len(image_files)}} test images")

    predictions = []

    for img_idx, img_path in enumerate(image_files):
        elapsed = time.time() - start_time
        if elapsed > TIMEOUT_SECONDS:
            print(f"WARNING: Timeout ({{elapsed:.0f}}s), stopping at {{img_idx}}/{{len(image_files)}}")
            break

        stem = img_path.stem
        try:
            image_id = int(stem.split("_")[-1])
        except ValueError:
            image_id = img_idx + 1

        # Run all models
        boxes_list, scores_list, labels_list = [], [], []
        img_w, img_h = 1, 1

        for model in models:
            results = model.predict(
                str(img_path), imgsz=IMGSZ, conf=CONF, iou=IOU_NMS,
                max_det=MAX_DET, augment=False, verbose=False, device=device,
            )
            if results and len(results[0].boxes) > 0:
                r = results[0]
                boxes_list.append(r.boxes.xyxy.cpu().numpy())
                scores_list.append(r.boxes.conf.cpu().numpy())
                labels_list.append(r.boxes.cls.cpu().numpy().astype(int))
                img_w = r.orig_img.shape[1]
                img_h = r.orig_img.shape[0]
            else:
                boxes_list.append(np.empty((0, 4)))
                scores_list.append(np.empty(0))
                labels_list.append(np.empty(0, dtype=int))

        # WBF merge
        boxes, scores_arr, labels_arr = wbf_single_image(
            boxes_list, scores_list, labels_list, img_w, img_h
        )

        for i in range(len(boxes)):
            x1, y1, x2, y2 = boxes[i]
            predictions.append({{
                "image_id": image_id,
                "category_id": int(labels_arr[i]),
                "bbox": [round(float(x1), 2), round(float(y1), 2),
                         round(float(x2 - x1), 2), round(float(y2 - y1), 2)],
                "score": round(float(scores_arr[i]), 4),
            }})

        if (img_idx + 1) % 50 == 0:
            elapsed = time.time() - start_time
            print(f"[{{img_idx+1}}/{{len(image_files)}}] {{len(predictions)}} dets, {{elapsed:.0f}}s")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(predictions, f)

    total_time = time.time() - start_time
    print(f"\\nDone! {{len(predictions)}} predictions in {{total_time:.1f}}s")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    run_inference(args.input, args.output)
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pick", nargs="*", default=None,
                        help="Manually pick model names (without .pt extension)")
    parser.add_argument("--wbf-iou", type=float, default=0.55,
                        help="WBF IoU threshold for generated run.py")
    parser.add_argument("--output-dir", default=None,
                        help="Export directory (default: ./export)")
    args = parser.parse_args()

    export_dir = Path(args.output_dir) if args.output_dir else EXPORT_DIR
    export_dir.mkdir(parents=True, exist_ok=True)

    # Find weight files
    if args.pick:
        weight_files = [WEIGHTS_DIR / f"{name}.pt" for name in args.pick]
        for wf in weight_files:
            if not wf.exists():
                print(f"ERROR: {wf} not found")
                return
        total_mb = sum(wf.stat().st_size / 1024 / 1024 for wf in weight_files)
    else:
        all_weights = sorted(WEIGHTS_DIR.glob("*.pt")) if WEIGHTS_DIR.exists() else []
        if not all_weights:
            print("No weights found in weights/ directory. Train models first.")
            return
        weight_files, total_mb = select_best_combination(all_weights, WEIGHT_BUDGET_MB, MAX_WEIGHT_FILES)

    print(f"\nSelected {len(weight_files)} models ({total_mb:.1f} MB):")
    for wf in weight_files:
        print(f"  {wf.name}: {wf.stat().st_size / 1024 / 1024:.1f} MB")

    if total_mb > WEIGHT_BUDGET_MB:
        print(f"\nWARNING: Total {total_mb:.1f} MB exceeds budget {WEIGHT_BUDGET_MB} MB!")
        print("Consider using fewer models or ONNX export.")

    # Copy weight files to export dir
    model_names = []
    for wf in weight_files:
        dst = export_dir / wf.name
        shutil.copy2(wf, dst)
        model_names.append(wf.name)
        print(f"  Copied {wf.name} -> {dst}")

    # Generate run.py
    run_py_content = generate_ensemble_run_py(model_names, wbf_iou=args.wbf_iou)
    run_py_path = export_dir / "run.py"
    with open(run_py_path, "w") as f:
        f.write(run_py_content)
    print(f"\nGenerated {run_py_path}")

    # Summary
    total_export_mb = sum(f.stat().st_size for f in export_dir.iterdir()) / 1024 / 1024
    n_py = len(list(export_dir.glob("*.py")))
    n_pt = len(list(export_dir.glob("*.pt")))
    print(f"\n{'='*60}")
    print(f"EXPORT COMPLETE: {export_dir}")
    print(f"  Weight files: {n_pt} / {MAX_WEIGHT_FILES} max")
    print(f"  Python files: {n_py} / 10 max")
    print(f"  Total size: {total_export_mb:.1f} MB / {MAX_ZIP_MB} MB max")
    print(f"\nTo build submission zip:")
    print(f"  cd {export_dir}")
    print(f'  zip -r submission_ensemble.zip . -x ".*"')
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
